name: DisStats
version: '${project.version}'
main: org.disstats.DisStats
api-version: '1.20'
load: STARTUP
depend: [DiscordSRV, Vault]
authors: [DevNguyen]
description: Send your stats to Discord
website: devnguyen.xyz

commands:
  statspl:
    description: View player statistics
    usage: /statspl
    permission: statsplugin.stats

permissions:
  statsplugin.stats:
    description: Allows access to view player statistics
    default: true
